version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"  # Exponiendo el puerto 3000 en localhost y el puerto 80 del contenedor
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge